import { ArrowUpRight, ChevronDown, ClipboardCheck, Trash2, X } from 'lucide-react'
import { useMemo, useState } from 'react'

export default function ItineraryBar({ items, onRemove, onClear, onOpenPlan, days, onChangeDays, tier, onChangeTier }) {
  const [isOpen, setIsOpen] = useState(false)
  const activityCost = useMemo(() => items.reduce((sum, place) => sum + place.cost, 0), [items])
  const daily = tier === 'comfort' ? 58 : tier === 'flash' ? 105 : 35
  const total = activityCost + daily * days
  return <div className="trip-dock-wrap">{isOpen && <section className="trip-sheet" aria-label="Your trip"><header><div><p>Your Cambodia trip</p><h2>{items.length ? `${items.length} saved stops` : 'Start with a spark'}</h2></div><button onClick={() => setIsOpen(false)} aria-label="Close trip"><X size={19} /></button></header>{items.length === 0 ? <div className="trip-empty"><span>✦</span><b>Your map is ready.</b><p>Choose a starter route, or tap a highlight to begin.</p></div> : <ul className="trip-list">{items.map(place => <li key={place.id}><span className="trip-list__icon">{place.icon}</span><div><b>{place.name}</b><small>{place.city} · ${place.cost}</small></div><button onClick={() => onRemove(place.id)} aria-label={`Remove ${place.name}`}><Trash2 size={16} /></button></li>)}</ul>}<div className="budget-settings"><div className="settings-top"><label>Trip length <strong>{days} days</strong></label><div className="stepper"><button onClick={() => onChangeDays(Math.max(1, days - 1))} aria-label="One fewer day">−</button><button onClick={() => onChangeDays(Math.min(21, days + 1))} aria-label="One more day">+</button></div></div><div className="tier-toggle">{[['value', '$ Value'], ['comfort', '$$ Comfort'], ['flash', '$$$ Splash']].map(([key, label]) => <button key={key} onClick={() => onChangeTier(key)} className={tier === key ? 'is-selected' : ''}>{label}</button>)}</div></div><div className="budget-summary"><p><span>Day-to-day · {days} × ${daily}</span><b>${daily * days}</b></p><p><span>Saved experiences</span><b>${activityCost}</b></p><p className="budget-total"><span>Rough total</span><b>${total}</b></p><small>Per person · stays, meals & local transport included</small></div>{items.length > 0 && <div className="trip-actions"><button onClick={onClear}>Clear plan</button><button onClick={() => { setIsOpen(false); onOpenPlan() }}>View itinerary <ArrowUpRight size={17} /></button></div>}</section>}<button className="trip-dock" onClick={() => setIsOpen(!isOpen)} aria-expanded={isOpen}><span className="dock-icon"><ClipboardCheck size={20} /></span><span><b>{items.length ? `${items.length} stop${items.length === 1 ? '' : 's'} saved` : 'Your trip is empty'}</b><small>{items.length ? `$${total} rough total` : 'Tap to make a plan'}</small></span><ChevronDown className={isOpen ? 'is-open' : ''} size={19} /></button></div>
}
